"use client";

import type { PublicWorkspaceState } from "@/lib/workspace-types";
import type { ProfileDraft } from "../ui-types";
import ModalShell from "./modal-shell";

export default function ProfileModal({ profile, draft, saving, otpEmail, otpCode, otpPending, onClose, onChange, onSave, onExport, onOtpEmailChange, onOtpCodeChange, onRequestOtp, onVerifyOtp }: { profile?: PublicWorkspaceState["profile"]; draft: ProfileDraft; saving: boolean; otpEmail: string; otpCode: string; otpPending: boolean; onClose: () => void; onChange: (patch: Partial<ProfileDraft>) => void; onSave: () => void; onExport: () => void; onOtpEmailChange: (value: string) => void; onOtpCodeChange: (value: string) => void; onRequestOtp: () => void; onVerifyOtp: () => void }) {
  return <ModalShell className="profile-modal" labelledBy="profile-settings-title" onClose={onClose}><p className="eyebrow">个人资料 · 学校验证</p><h2 id="profile-settings-title">个人资料与校内验证</h2><p className="modal-intro">资料会保存到当前工作区。校内互助只会在邮箱验证并匹配管理员配置的学校域名后开放，不会展示虚假积分。</p><div className="form-grid"><label>显示名称<input value={draft.displayName} maxLength={80} onChange={(event) => onChange({ displayName: event.target.value })} placeholder="例如 林同学" /></label><label>学校名称<input value={draft.school} maxLength={120} onChange={(event) => onChange({ school: event.target.value })} placeholder="由学校邮箱域名自动匹配或手动记录" /></label><label className="full-field">复习目标<input value={draft.examGoal} maxLength={240} onChange={(event) => onChange({ examGoal: event.target.value })} placeholder="例如 在期末前完成一轮高频考点复习" /></label><label>时区（IANA）<input list="timezone-options" value={draft.timezone} maxLength={64} onChange={(event) => onChange({ timezone: event.target.value })} placeholder="Asia/Shanghai" /><datalist id="timezone-options"><option value="Asia/Shanghai" /><option value="Asia/Hong_Kong" /><option value="Asia/Tokyo" /><option value="Asia/Singapore" /><option value="Europe/London" /><option value="America/New_York" /><option value="America/Los_Angeles" /><option value="UTC" /></datalist></label><label>每日计划开始时间<input type="time" value={draft.studyDayStart} onChange={(event) => onChange({ studyDayStart: event.target.value })} /></label></div><section className={`verification-card ${profile?.verified ? "verified" : ""}`}><div><b>{profile?.verified ? "学校边界已验证" : profile?.email ? "邮箱已记录，尚未完成学校验证" : "未验证邮箱"}</b><small>{profile?.verified ? `${profile.school} · ${profile.email}` : "使用学校邮箱并完成一次真实邮件验证码验证。"}</small></div><span>{profile?.verified ? "✓" : "!"}</span></section><div className="otp-grid"><label>验证邮箱<input type="email" value={otpEmail} onChange={(event) => onOtpEmailChange(event.target.value)} placeholder="例如 liming@stu.example.edu.cn" autoComplete="email" /></label><label>验证码<input inputMode="numeric" maxLength={6} value={otpCode} onChange={(event) => onOtpCodeChange(event.target.value.replace(/\D/g, "").slice(0, 6))} placeholder="6 位数字" autoComplete="one-time-code" /></label></div><div className="profile-actions"><button className="outline" type="button" onClick={onRequestOtp} disabled={otpPending || !otpEmail.trim()}>{otpPending ? "处理中…" : "发送邮箱验证码"}</button><button className="outline" type="button" onClick={onVerifyOtp} disabled={otpPending || otpCode.length !== 6 || !otpEmail.trim()}>验证邮箱</button><button className="primary" type="button" onClick={onSave} disabled={saving}>{saving ? "保存中…" : "保存个人资料"}</button><button className="outline" type="button" onClick={onExport}>导出工作区数据（JSON）</button></div><p className="session-note">验证码由你配置的邮件服务发送；未配置邮件服务时，系统会明确拒绝验证，不会在页面上伪造成功。导出文件包含全部课程、资料元数据、分析与练习记录，请按个人数据保管。</p></ModalShell>;
}

